// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOrrGtOy-7PQqQUgn6okUlP3wBAPujFsY',
    appId: '1:603333503353:web:e41d8a9a3ee630b89d27a8',
    messagingSenderId: '603333503353',
    projectId: 'instagram-app-de9aa',
    authDomain: 'instagram-app-de9aa.firebaseapp.com',
    storageBucket: 'instagram-app-de9aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi2cdCNxDLGNsEdRlFG2EDlOQ4TTRA_rE',
    appId: '1:603333503353:android:c8224bfcf737cc539d27a8',
    messagingSenderId: '603333503353',
    projectId: 'instagram-app-de9aa',
    storageBucket: 'instagram-app-de9aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGTrJ0-lEAK2-8H2wtGoh0uWz_OSNJ3OE',
    appId: '1:603333503353:ios:a79f7f7423f5c0709d27a8',
    messagingSenderId: '603333503353',
    projectId: 'instagram-app-de9aa',
    storageBucket: 'instagram-app-de9aa.appspot.com',
    iosClientId: '603333503353-vbvj32gsbuk7kght89evgqvplj5as5cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGTrJ0-lEAK2-8H2wtGoh0uWz_OSNJ3OE',
    appId: '1:603333503353:ios:6691505e1a70e8ea9d27a8',
    messagingSenderId: '603333503353',
    projectId: 'instagram-app-de9aa',
    storageBucket: 'instagram-app-de9aa.appspot.com',
    iosClientId: '603333503353-gf0fbn2b89cgfj7eso38qccqkr2pelll.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramApp.RunnerTests',
  );
}
